import 'package:flutter/material.dart';import 'package:abdelhamed_s_application9/core/app_export.dart';import 'package:abdelhamed_s_application9/widgets/custom_elevated_button.dart';import 'package:abdelhamed_s_application9/widgets/custom_rating_bar.dart';import 'package:abdelhamed_s_application9/widgets/custom_text_form_field.dart';import 'bloc/onehundredtwentyone_bloc.dart';import 'models/onehundredtwentyone_item_model.dart';import 'models/onehundredtwentyone_model.dart';import 'widgets/onehundredtwentyone_item_widget.dart';class OnehundredtwentyoneBottomsheet extends StatelessWidget {const OnehundredtwentyoneBottomsheet({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<OnehundredtwentyoneBloc>(create: (context) => OnehundredtwentyoneBloc(OnehundredtwentyoneState(onehundredtwentyoneModelObj: OnehundredtwentyoneModel()))..add(OnehundredtwentyoneInitialEvent()), child: OnehundredtwentyoneBottomsheet()); } 
@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 17.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.customBorderTL30), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(width: 72.h, child: Divider(color: appTheme.blueGray10001)), SizedBox(height: 15.v), Text("lbl_product_rating".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 11.v), _buildRatingBar(context), SizedBox(height: 14.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_add_comment".tr, style: CustomTextStyles.titleSmall15_1))), SizedBox(height: 7.v), BlocSelector<OnehundredtwentyoneBloc, OnehundredtwentyoneState, TextEditingController?>(selector: (state) => state.commentController, builder: (context, commentController) {return CustomTextFormField(controller: commentController, hintText: "msg_type_your_comment".tr, hintStyle: theme.textTheme.bodyMedium!, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 30.v, 30.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgCamera, height: 16.v, width: 18.h)), suffixConstraints: BoxConstraints(maxHeight: 150.v), maxLines: 8, borderDecoration: TextFormFieldStyleHelper.outlineGray, fillColor: appTheme.gray10003);}), SizedBox(height: 9.v), _buildOneHundredTwentyOne(context), SizedBox(height: 18.v), CustomElevatedButton(text: "lbl_add_rating".tr), SizedBox(height: 15.v)])); } 
/// Section Widget
Widget _buildRatingBar(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 78.h, vertical: 12.v), decoration: AppDecoration.outlineGray20004.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: CustomRatingBar(initialRating: 4, itemSize: 24)); } 
/// Section Widget
Widget _buildOneHundredTwentyOne(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: SizedBox(height: 59.v, child: BlocSelector<OnehundredtwentyoneBloc, OnehundredtwentyoneState, OnehundredtwentyoneModel?>(selector: (state) => state.onehundredtwentyoneModelObj, builder: (context, onehundredtwentyoneModelObj) {return ListView.separated(padding: EdgeInsets.only(right: 191.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 5.h);}, itemCount: onehundredtwentyoneModelObj?.onehundredtwentyoneItemList.length ?? 0, itemBuilder: (context, index) {OnehundredtwentyoneItemModel model = onehundredtwentyoneModelObj?.onehundredtwentyoneItemList[index] ?? OnehundredtwentyoneItemModel(); return OnehundredtwentyoneItemWidget(model, onTapBtnClose: () {onTapBtnClose(context);});});}))); } 

/// Navigates to the previous screen.
onTapBtnClose(BuildContext context) { NavigatorService.goBack(); } 
 }
