import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:abdelhamed_s_application9/core/app_export.dart';import 'package:abdelhamed_s_application9/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:abdelhamed_s_application9/widgets/app_bar/appbar_subtitle.dart';import 'package:abdelhamed_s_application9/widgets/app_bar/appbar_trailing_iconbutton_two.dart';import 'package:abdelhamed_s_application9/widgets/app_bar/custom_app_bar.dart';import 'package:abdelhamed_s_application9/widgets/custom_elevated_button.dart';import 'package:abdelhamed_s_application9/widgets/custom_outlined_button.dart';import 'package:abdelhamed_s_application9/widgets/custom_text_form_field.dart';import 'bloc/onehundredfortyfour_bloc.dart';import 'models/onehundredfortyfour_model.dart';class OnehundredfortyfourScreen extends StatelessWidget {const OnehundredfortyfourScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<OnehundredfortyfourBloc>(create: (context) => OnehundredfortyfourBloc(OnehundredfortyfourState(onehundredfortyfourModelObj: OnehundredfortyfourModel()))..add(OnehundredfortyfourInitialEvent()), child: OnehundredfortyfourScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 23.v), child: Column(children: [_buildClose(context), SizedBox(height: 20.v), Text("msg_enter_code_coupon".tr, style: theme.textTheme.titleMedium), SizedBox(height: 15.v), CustomOutlinedButton(height: 50.v, text: "msg_type_certification".tr, margin: EdgeInsets.symmetric(horizontal: 13.h), buttonStyle: CustomButtonStyles.outlineGrayTL10, buttonTextStyle: CustomTextStyles.bodyMedium15), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 1.h, right: 3.h), child: BlocSelector<OnehundredfortyfourBloc, OnehundredfortyfourState, TextEditingController?>(selector: (state) => state.descriptionController, builder: (context, descriptionController) {return CustomTextFormField(controller: descriptionController, hintText: "msg_within_5_to_10_minutes".tr, hintStyle: CustomTextStyles.bodySmallOnSecondaryContainer, textInputAction: TextInputAction.done, maxLines: 4, contentPadding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 6.v));})), SizedBox(height: 5.v)])), bottomNavigationBar: _buildApply(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 65.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 20.h, top: 1.v, bottom: 1.v)), centerTitle: true, title: AppbarSubtitle(text: "msg_coupons_and_certificates".tr), actions: [AppbarTrailingIconbuttonTwo(imagePath: ImageConstant.imgBag, margin: EdgeInsets.symmetric(horizontal: 21.h, vertical: 3.v))]); } 
/// Section Widget
Widget _buildClose(BuildContext context) { return Container(width: 342.h, margin: EdgeInsets.only(left: 1.h), padding: EdgeInsets.symmetric(horizontal: 27.h, vertical: 8.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup1276), fit: BoxFit.cover)), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgCloseWhiteA70064x90, height: 64.v, width: 90.h, margin: EdgeInsets.only(top: 11.v, bottom: 10.v), onTap: () {onTapImgClose(context);}), Padding(padding: EdgeInsets.only(left: 19.h), child: SizedBox(height: 86.v, child: VerticalDivider(width: 2.h, thickness: 2.v, color: appTheme.whiteA700.withOpacity(0.2), endIndent: 1.h))), Spacer(), Container(width: 118.h, margin: EdgeInsets.only(top: 11.v, right: 27.h, bottom: 10.v), child: Text("lbl_coupon_code".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.headlineMediumWhiteA700.copyWith(height: 1.07)))])); } 
/// Section Widget
Widget _buildApply(BuildContext context) { return CustomElevatedButton(text: "lbl_apply".tr, margin: EdgeInsets.only(left: 19.h, right: 19.h, bottom: 34.v)); } 

/// Navigates to the previous screen.
onTapImgClose(BuildContext context) { NavigatorService.goBack(); } 
 }
